[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "searcher"
version = "0.6.0"
description = "Modul zum Durchsuchen von Clip-Metadaten (Metadata-API oder CSV)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["searcher*"]