[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "searcher"
description = "Modul zum Durchsuchen von Clip-Metadaten"
readme = "README.md"
requires-python = ">=3.11"
dynamic = ["version"]
dependencies = [
    "python-dotenv",
]


[project.optional-dependencies]
api = [
    "toolbox @ git+https://github.com/PROGRESS-MAM/TOOLBOX.git@main",
]


[tool.setuptools.dynamic]
version = {attr = "searcher.searcher.app_version"}


[tool.setuptools.packages.find]
where = ["."]
include = ["searcher*"]